services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_yazlab
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin

  authservice:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: auth_service
    

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
    depends_on:
      - mongodb

  eventservice:
    build:
      context: ./EventService
      dockerfile: Dockerfile
    container_name: event_service
    environment:
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - mongodb

  ticketservice:
    build:
      context: ./TicketService
      dockerfile: Dockerfile
    container_name: ticket_service
    environment:
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - mongodb

  dispatcher:
    build:
      context: ./Dispatcher
      dockerfile: Dockerfile
    container_name: api_dispatcher
    ports:
      - "5000:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - authservice
      - eventservice
      - ticketservice

volumes:
  mongo_data: